DROP TABLE IF EXISTS TypesUsers;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS Countries;

DROP TABLE IF EXISTS FilmsCountries;

DROP TABLE IF EXISTS Films;

DROP TABLE IF EXISTS Peoples;

DROP TABLE IF EXISTS Accounts;

DROP TABLE IF EXISTS Directors;

DROP TABLE IF EXISTS Actors;

CREATE TABLE TypesUsers(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    type VARCHAR(200) NOT NULL UNIQUE,
    access_level INT NOT NULL UNIQUE
);

CREATE TABLE Users(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    typeID INT NOT NULL,
    fio VARCHAR(200) NOT NULL,
    phone VARCHAR(200) NOT NULL UNIQUE,
    FOREIGN KEY(typeID)
        REFERENCES TypesUsers(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Countries(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Films(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    relyear VARCHAR(200) NOT NULL,
    runtime VARCHAR(200) NOT NULL,
    name VARHCAR(200) NOT NULL
);

CREATE TABLE FilmsCountries(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    countryID INT NOT NULL,
    filmID INT NOT NULL,
    FOREIGN KEY(countryID)
        REFERENCES Countries(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY(filmID)
        REFERENCES Films(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Accounts(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    userID INT NOT NULL,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Peoples(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Directors(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    peopleID INT NOT NULL,
    filmID INT NOT NULL,
    FOREIGN KEY(peopleID)
        REFERENCES Peoples(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY(filmID)
        REFERENCES Films(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Actors(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    peopleID INT NOT NULL,
    filmID INT NOT NULL,
    FOREIGN KEY(peopleID)
        REFERENCES Peoples(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY(filmID)
        REFERENCES Films(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);
